CREATE TABLE IF NOT EXISTS CUSTOMERS(
    NAME TEXT PRIMARY KEY,
    AGE INTEGER,
    PRODUCT TEXT,
    PRODUCT_ORIGIN TEXT,
    PRODUCT_PRICE INTEGER
);

INSERT INTO CUSTOMERS (NAME, AGE, PRODUCT, PRODUCT_ORIGIN, PRODUCT_PRICE)VALUES
('Abraham Doe', 30, 'Laptop', 'USA', 1200),
('Corrie', 25, 'Smartphone', 'China', 800),
('Alice Johnson', 28, 'Tablet', 'South Korea', 600),
('Bob Brown', 35, 'Headphones', 'Germany', 150),
('Chorlie Davis', 22, 'Smartwatch', 'Japan', 200);

SELECT * FROM CUSTOMERS;

SELECT NAME,PRODUCT
FROM CUSTOMERS
WHERE NAME LIKE 'a%';

SELECT NAME, PRODUCT
FROM CUSTOMERS
WHERE NAME LIKE '%or%';

SELECT NAME, PRODUCT
FROM CUSTOMERS
WHERE PRODUCT_ORIGIN = 'USA';

SELECT DISTINCT PRODUCT_ORIGIN
FROM CUSTOMERS; 